# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  pull_request:
    branches: [ "master" ]
    paths:
    - '**.cs'
    - '**.csproj'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    
    - name: Install dependencies
      run: dotnet restore ./SkribeSeinSDBot.csproj
    - name: Build
      run: dotnet build ./SkribeSeinSDBot.csproj --configuration Release --no-restore
      
    - name: Build
      run: dotnet publish ./SkribeSeinSDBot.csproj -c Release -f net7.0 --runtime win-x64 --self-contained true /p:PublishSingleFile=true
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.3
      with:
        # Artifact name
        name: jellychan# optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: /home/runner/work/MatrixAutomatic1111Bot/MatrixAutomatic1111Bot/bin/Release/net7.0/win-x64/publish/
        # The desired behavior if no files are found using the provided path.
